### ISSUE TITLE
Unable to connect to RCON on unRAID server

### ISSUE THREAD

**Issue by HAMCORE** [itzg/docker-mc-backup#153]
I am having a lot of issues getting this container to communicate with my main Minecraft itzg container.

I have set the server port, rcon port, and rcon password (all default) variables and all of the drive mounts.

`localhost` and `mc` (name of my Minecraft container) do not work for RCON_HOST.

Network is set to bridge in unRAID

**Comment by itzg** [comment]
Since I'm not familiar with Unraid, how are the containers configured there? I party ask because manually getting the name resolution on docker networks to line up is surprisingly hard. What always works for me is letting compose coordinate that as int he example

https://github.com/itzg/docker-mc-backup/blob/master/examples/docker-compose.yml

But I'm not sure if that's an option for you.
