### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by davydehaas98** [itzg/docker-mc-backup#21]
Hi,
Can the TZ environment be added to the image?
It would be nice if my timezone lines up with the timezone in my minecraft containers :)

**Comment by itzg** [comment]
With containers you can add as many environment variables as you want, so just go ahead and use `TZ` and it is documented:

https://github.com/itzg/docker-minecraft-server#timezone-configuration

I minimize the number of variables I predeclare because some docker UIs are too "sticky" and have poor usability with image declared variables.

**Comment by davydehaas98** [comment]
Hi, I did that but it seems like the image does not pick it up from the environment variables and instead uses the standard time. :(
The TZ in my pipeline and .env file is set to "Europe/Amsterdam"

My current docker-compose file as reference: https://github.com/davydehaas98/server/blob/main/enabled/docker-compose.minecraft-vanilla.yml

**Comment by itzg** [comment]
### Note to self

Need to add `tzdata` package at

https://github.com/itzg/docker-mc-backup/blob/61892f832d01a2448973191b520b4f10a426b403/Dockerfile#L41-L44

**Comment by itzg** [comment]
The latest image now includes timezone data, so this should now be working.

**Comment by davydehaas98** [comment]
It does. Thank you!
